import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsible: true,
      collapsed: false,
      items: [
        'intro',
        'getting-started',
        'quizzes',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      collapsible: false,
      collapsed: true,
      items: [
        'module1-ros2/module1-intro',
        'module1-ros2/chapter01/introduction-to-physical-ai',
        'module1-ros2/chapter02/humanoid-robotics-hardware',
        'module1-ros2/chapter03/setting-up-development-environment',
        'module1-ros2/quiz/module1-quiz',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      collapsible: true,
      collapsed: false,
      items: [
        'module2-gazebounity/module2-intro',
        'module2-gazebounity/chapter04/introduction-to-simulation-environments',
        'module2-gazebounity/chapter05/setting-up-simulation-environments',
        'module2-gazebounity/chapter06/digital-twin-concepts',
        'module2-gazebounity/chapter07/kinematics-dynamics-humanoids',
        'module2-gazebounity/chapter08/balance-locomotion-humanoids',
        'module2-gazebounity/chapter09/manipulation-grasping-humanoids',
        'module2-gazebounity/quiz/module2-quiz',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      collapsible: true,
      collapsed: false,
      items: [
        'module3-nvidiaisaac/module3-intro',
        'module3-nvidiaisaac/chapter10/computer-vision-robotics',
        'module3-nvidiaisaac/chapter11/sensor-fusion-state-estimation',
        'module3-nvidiaisaac/chapter12/proprioception-tactile-sensing',
        'module3-nvidiaisaac/chapter13/motion-planning-bipedal-locomotion',
        'module3-nvidiaisaac/chapter14/manipulation-grasping-strategies',
        'module3-nvidiaisaac/quiz/module3-quiz',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      collapsible: true,
      collapsed: false,
      items: [
        'module4-vla/module4-intro',
        'module4-vla/chapter15/reinforcement-learning-robot-control',
        'module4-vla/chapter16/imitation-learning-behavior-cloning',
        'module4-vla/chapter17/sim-to-real-transfer',
        'module4-vla/chapter18/capstone-project',
        'module4-vla/quiz/module4-quiz',
      ],
    },
  ],

  // Keep the original auto-generated sidebar as well if needed
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
